### ISSUE TITLE
Folder watching documentation appears to be inaccurate

### ISSUE THREAD

**Issue by danielsamuels** [andreaskoch/go-fswatch#2]
Judging by the actual code, it seems like there was an API change without the folderWatcher examples in the documentation being updated.

**Comment by andreaskoch** [comment]
Hi Daniel,
thanks for pointing that out. I changed the method signatures a while ago and must have forgotten to update the documentation. I will fix that by tomorrow.

Greetings
 - Andy

**Comment by andreaskoch** [comment]
I have updated the [README](https://github.com/andreaskoch/go-fswatch/blob/ecea47604a702853c881a7dd161fead47ce8467f/README.md) and the code comments (see: ecea47604a702853c881a7dd161fead47ce8467f).

You can see a working example in the **live-reload** feature of my [markdown webserver "allmark"](https://allmark.io/) at [github.com/andreaskoch/allmark/blob/master/src/allmark.io/modules/dataaccess/filesystem/watcher.go](https://github.com/andreaskoch/allmark/blob/master/src/allmark.io/modules/dataaccess/filesystem/watcher.go):

```go
checkIntervalInSeconds := 1

recurse := true
skipNoFiles := func(path string) bool {
  return false
}

folderWatcher := fswatch.NewFolderWatcher(directoryPath, recurse, skipNoFiles, checkIntervalInSeconds)
folderWatcher.Start()

// the go-routine which waits for changes
go func() {
  running := true
  for running {

    select {
    case <-folderWatcher.Modified():
      backChannel <- true

    case <-folderWatcher.Moved():
      running = false

    case <-folderWatcher.Stopped():
      running = false
    }
  }
}()
```

Greetings
Andy
